<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>lab2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="Lab2_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lab2_files/libs/quarto-html/quarto.js"></script>
<script src="Lab2_files/libs/quarto-html/popper.min.js"></script>
<script src="Lab2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lab2_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lab2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lab2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lab2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lab2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lab2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<p>Problem 0 - Import the data and declare your package dependencies.</p>
<div id="cell-1" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Dependencies</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> <span class="op">*</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-2" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>avocados <span class="op">=</span> pd.read_csv(<span class="st">'avocado-updated-2020.csv.zip'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(avocados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             date  average_price  total_volume        4046  ...  xlarge_bags          type  year             geography
0      2015-01-04           1.22      40873.28     2819.50  ...         0.00  conventional  2015                Albany
1      2015-01-04           1.79       1373.95       57.42  ...         0.00       organic  2015                Albany
2      2015-01-04           1.00     435021.49   364302.39  ...         0.00  conventional  2015               Atlanta
3      2015-01-04           1.76       3846.69     1500.15  ...         0.00       organic  2015               Atlanta
4      2015-01-04           1.08     788025.06    53987.31  ...         0.00  conventional  2015  Baltimore/Washington
...           ...            ...           ...         ...  ...          ...           ...   ...                   ...
33040  2020-11-29           1.47    1583056.27    67544.48  ...     27974.75       organic  2020            Total U.S.
33041  2020-11-29           0.91    5811114.22  1352877.53  ...     61524.13  conventional  2020                  West
33042  2020-11-29           1.48     289961.27    13273.75  ...         0.00       organic  2020                  West
33043  2020-11-29           0.67     822818.75   234688.01  ...       809.83  conventional  2020   West Tex/New Mexico
33044  2020-11-29           1.35      24106.58     1236.96  ...         0.00       organic  2020   West Tex/New Mexico

[33045 rows x 13 columns]
             date  average_price  total_volume        4046  ...  xlarge_bags          type  year             geography
0      2015-01-04           1.22      40873.28     2819.50  ...         0.00  conventional  2015                Albany
1      2015-01-04           1.79       1373.95       57.42  ...         0.00       organic  2015                Albany
2      2015-01-04           1.00     435021.49   364302.39  ...         0.00  conventional  2015               Atlanta
3      2015-01-04           1.76       3846.69     1500.15  ...         0.00       organic  2015               Atlanta
4      2015-01-04           1.08     788025.06    53987.31  ...         0.00  conventional  2015  Baltimore/Washington
...           ...            ...           ...         ...  ...          ...           ...   ...                   ...
33040  2020-11-29           1.47    1583056.27    67544.48  ...     27974.75       organic  2020            Total U.S.
33041  2020-11-29           0.91    5811114.22  1352877.53  ...     61524.13  conventional  2020                  West
33042  2020-11-29           1.48     289961.27    13273.75  ...         0.00       organic  2020                  West
33043  2020-11-29           0.67     822818.75   234688.01  ...       809.83  conventional  2020   West Tex/New Mexico
33044  2020-11-29           1.35      24106.58     1236.96  ...         0.00       organic  2020   West Tex/New Mexico

[33045 rows x 13 columns]</code></pre>
</div>
</div>
<p>Problem 1 - Briefly describe the data set. What information does it contain?</p>
<p>The avocado dataset from Kaggle contains detailed information on avocado prices and sales volume in different parts of the United States from January 4th 2015 to May 17th 2020. This data set includes columns such as the date, average price, total sales of small, large, and extra-large avocadoes, total number of avocado bags sold, the type of avocado, where in the US the data was collected, and the year the data was collected.</p>
<p>Problem 2 - Clean the data in any way you see fit.</p>
<div id="cell-5" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Used ChatGPT to help create a new column for region type</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new column for region type (Major Region, State, Metro Area)</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> categorize_region(geography):</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> geography <span class="kw">in</span> [<span class="st">'Total U.S.'</span>, <span class="st">'West'</span>, <span class="st">'Northeast'</span>, <span class="st">'South'</span>, <span class="st">'Midwest'</span>]:</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'Major Region'</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> geography <span class="kw">in</span> [<span class="st">'California'</span>, <span class="st">'Texas'</span>, <span class="st">'Florida'</span>, <span class="st">'New York'</span>]:</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'State'</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'Metro Area'</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>avocados[<span class="st">'region_type'</span>] <span class="op">=</span> avocados[<span class="st">'geography'</span>].<span class="bu">apply</span>(categorize_region)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-6" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(avocados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             date  average_price  total_volume        4046  ...          type  year             geography   region_type
0      2015-01-04           1.22      40873.28     2819.50  ...  conventional  2015                Albany    Metro Area
1      2015-01-04           1.79       1373.95       57.42  ...       organic  2015                Albany    Metro Area
2      2015-01-04           1.00     435021.49   364302.39  ...  conventional  2015               Atlanta    Metro Area
3      2015-01-04           1.76       3846.69     1500.15  ...       organic  2015               Atlanta    Metro Area
4      2015-01-04           1.08     788025.06    53987.31  ...  conventional  2015  Baltimore/Washington    Metro Area
...           ...            ...           ...         ...  ...           ...   ...                   ...           ...
33040  2020-11-29           1.47    1583056.27    67544.48  ...       organic  2020            Total U.S.  Major Region
33041  2020-11-29           0.91    5811114.22  1352877.53  ...  conventional  2020                  West  Major Region
33042  2020-11-29           1.48     289961.27    13273.75  ...       organic  2020                  West  Major Region
33043  2020-11-29           0.67     822818.75   234688.01  ...  conventional  2020   West Tex/New Mexico    Metro Area
33044  2020-11-29           1.35      24106.58     1236.96  ...       organic  2020   West Tex/New Mexico    Metro Area

[33045 rows x 14 columns]
             date  average_price  total_volume        4046  ...          type  year             geography   region_type
0      2015-01-04           1.22      40873.28     2819.50  ...  conventional  2015                Albany    Metro Area
1      2015-01-04           1.79       1373.95       57.42  ...       organic  2015                Albany    Metro Area
2      2015-01-04           1.00     435021.49   364302.39  ...  conventional  2015               Atlanta    Metro Area
3      2015-01-04           1.76       3846.69     1500.15  ...       organic  2015               Atlanta    Metro Area
4      2015-01-04           1.08     788025.06    53987.31  ...  conventional  2015  Baltimore/Washington    Metro Area
...           ...            ...           ...         ...  ...           ...   ...                   ...           ...
33040  2020-11-29           1.47    1583056.27    67544.48  ...       organic  2020            Total U.S.  Major Region
33041  2020-11-29           0.91    5811114.22  1352877.53  ...  conventional  2020                  West  Major Region
33042  2020-11-29           1.48     289961.27    13273.75  ...       organic  2020                  West  Major Region
33043  2020-11-29           0.67     822818.75   234688.01  ...  conventional  2020   West Tex/New Mexico    Metro Area
33044  2020-11-29           1.35      24106.58     1236.96  ...       organic  2020   West Tex/New Mexico    Metro Area

[33045 rows x 14 columns]</code></pre>
</div>
</div>
<div id="cell-7" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Renaming columns for clarity</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>clean_df <span class="op">=</span> avocados.rename(columns<span class="op">=</span>{</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'4046'</span>: <span class="st">'small_avocados'</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'4225'</span>: <span class="st">'large_avocados'</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'4770'</span>: <span class="st">'xl_avocados'</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Total Volume'</span>: <span class="st">'total_avocado_volume'</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Total Bags'</span>: <span class="st">'total_bags'</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'geography'</span>: <span class="st">'region'</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-8" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clean_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             date  average_price  total_volume  small_avocados  ...          type  year                region   region_type
0      2015-01-04           1.22      40873.28         2819.50  ...  conventional  2015                Albany    Metro Area
1      2015-01-04           1.79       1373.95           57.42  ...       organic  2015                Albany    Metro Area
2      2015-01-04           1.00     435021.49       364302.39  ...  conventional  2015               Atlanta    Metro Area
3      2015-01-04           1.76       3846.69         1500.15  ...       organic  2015               Atlanta    Metro Area
4      2015-01-04           1.08     788025.06        53987.31  ...  conventional  2015  Baltimore/Washington    Metro Area
...           ...            ...           ...             ...  ...           ...   ...                   ...           ...
33040  2020-11-29           1.47    1583056.27        67544.48  ...       organic  2020            Total U.S.  Major Region
33041  2020-11-29           0.91    5811114.22      1352877.53  ...  conventional  2020                  West  Major Region
33042  2020-11-29           1.48     289961.27        13273.75  ...       organic  2020                  West  Major Region
33043  2020-11-29           0.67     822818.75       234688.01  ...  conventional  2020   West Tex/New Mexico    Metro Area
33044  2020-11-29           1.35      24106.58         1236.96  ...       organic  2020   West Tex/New Mexico    Metro Area

[33045 rows x 14 columns]
             date  average_price  total_volume  small_avocados  ...          type  year                region   region_type
0      2015-01-04           1.22      40873.28         2819.50  ...  conventional  2015                Albany    Metro Area
1      2015-01-04           1.79       1373.95           57.42  ...       organic  2015                Albany    Metro Area
2      2015-01-04           1.00     435021.49       364302.39  ...  conventional  2015               Atlanta    Metro Area
3      2015-01-04           1.76       3846.69         1500.15  ...       organic  2015               Atlanta    Metro Area
4      2015-01-04           1.08     788025.06        53987.31  ...  conventional  2015  Baltimore/Washington    Metro Area
...           ...            ...           ...             ...  ...           ...   ...                   ...           ...
33040  2020-11-29           1.47    1583056.27        67544.48  ...       organic  2020            Total U.S.  Major Region
33041  2020-11-29           0.91    5811114.22      1352877.53  ...  conventional  2020                  West  Major Region
33042  2020-11-29           1.48     289961.27        13273.75  ...       organic  2020                  West  Major Region
33043  2020-11-29           0.67     822818.75       234688.01  ...  conventional  2020   West Tex/New Mexico    Metro Area
33044  2020-11-29           1.35      24106.58         1236.96  ...       organic  2020   West Tex/New Mexico    Metro Area

[33045 rows x 14 columns]</code></pre>
</div>
</div>
<p>Problem 3 - Which major geographical region sold the most total organic, small Hass avocados in 2017?</p>
<div id="cell-10" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Used ChatGPT to help me filter the dataframe and calculate total small avocado sales by region. </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the DataFrame for the year 2017 and organic avocados</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>df_2017_organic <span class="op">=</span> clean_df[(clean_df[<span class="st">'year'</span>] <span class="op">==</span> <span class="dv">2017</span>) <span class="op">&amp;</span> (clean_df[<span class="st">'type'</span>] <span class="op">==</span> <span class="st">'organic'</span>)]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to only include rows where the region is a 'Major Region'</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>major_regions <span class="op">=</span> [<span class="st">'Total U.S.'</span>, <span class="st">'West'</span>, <span class="st">'Northeast'</span>, <span class="st">'South'</span>, <span class="st">'Midwest'</span>]</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>df_major_regions <span class="op">=</span> df_2017_organic[df_2017_organic[<span class="st">'region'</span>].isin(major_regions)]</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by region and calculate the total small avocado sales</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>total_small_avocados_by_region <span class="op">=</span> df_major_regions.groupby(<span class="st">'region'</span>)[<span class="st">'small_avocados'</span>].<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-11" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_small_avocados_by_region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>region
Northeast      925832.36
Total U.S.    6882024.42
West          1870206.29
Name: small_avocados, dtype: float64
region
Northeast      925832.36
Total U.S.    6882024.42
West          1870206.29
Name: small_avocados, dtype: float64</code></pre>
</div>
</div>
<p>Total U.S. is the major geographical region that sold the most small avocados in 2017 with a total of 6882024.42 small avocados sold.</p>
<p>Problem 4 - Split the date variable into month, day, and year variables. In which month is the highest average volume of avocado sales?</p>
<div id="cell-14" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Use ChatGPT to convert the date column into three seperate columns for year, month, and day</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>clean_df[<span class="st">'date'</span>] <span class="op">=</span> pd.to_datetime(clean_df[<span class="st">'date'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'%Y-%m-</span><span class="sc">%d</span><span class="st">'</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>clean_df[<span class="st">'year'</span>] <span class="op">=</span> clean_df[<span class="st">'date'</span>].dt.year</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>clean_df[<span class="st">'month'</span>] <span class="op">=</span> clean_df[<span class="st">'date'</span>].dt.month</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>clean_df[<span class="st">'day'</span>] <span class="op">=</span> clean_df[<span class="st">'date'</span>].dt.day</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>clean_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">average_price</th>
<th data-quarto-table-cell-role="th">total_volume</th>
<th data-quarto-table-cell-role="th">small_avocados</th>
<th data-quarto-table-cell-role="th">large_avocados</th>
<th data-quarto-table-cell-role="th">xl_avocados</th>
<th data-quarto-table-cell-role="th">total_bags</th>
<th data-quarto-table-cell-role="th">small_bags</th>
<th data-quarto-table-cell-role="th">large_bags</th>
<th data-quarto-table-cell-role="th">xlarge_bags</th>
<th data-quarto-table-cell-role="th">type</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">region_type</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2015-01-04</td>
<td>1.22</td>
<td>40873.28</td>
<td>2819.50</td>
<td>28287.42</td>
<td>49.90</td>
<td>9716.46</td>
<td>9186.93</td>
<td>529.53</td>
<td>0.00</td>
<td>conventional</td>
<td>2015</td>
<td>Albany</td>
<td>Metro Area</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2015-01-04</td>
<td>1.79</td>
<td>1373.95</td>
<td>57.42</td>
<td>153.88</td>
<td>0.00</td>
<td>1162.65</td>
<td>1162.65</td>
<td>0.00</td>
<td>0.00</td>
<td>organic</td>
<td>2015</td>
<td>Albany</td>
<td>Metro Area</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2015-01-04</td>
<td>1.00</td>
<td>435021.49</td>
<td>364302.39</td>
<td>23821.16</td>
<td>82.15</td>
<td>46815.79</td>
<td>16707.15</td>
<td>30108.64</td>
<td>0.00</td>
<td>conventional</td>
<td>2015</td>
<td>Atlanta</td>
<td>Metro Area</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2015-01-04</td>
<td>1.76</td>
<td>3846.69</td>
<td>1500.15</td>
<td>938.35</td>
<td>0.00</td>
<td>1408.19</td>
<td>1071.35</td>
<td>336.84</td>
<td>0.00</td>
<td>organic</td>
<td>2015</td>
<td>Atlanta</td>
<td>Metro Area</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2015-01-04</td>
<td>1.08</td>
<td>788025.06</td>
<td>53987.31</td>
<td>552906.04</td>
<td>39995.03</td>
<td>141136.68</td>
<td>137146.07</td>
<td>3990.61</td>
<td>0.00</td>
<td>conventional</td>
<td>2015</td>
<td>Baltimore/Washington</td>
<td>Metro Area</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">33040</td>
<td>2020-11-29</td>
<td>1.47</td>
<td>1583056.27</td>
<td>67544.48</td>
<td>97996.46</td>
<td>2617.17</td>
<td>1414878.10</td>
<td>906711.52</td>
<td>480191.83</td>
<td>27974.75</td>
<td>organic</td>
<td>2020</td>
<td>Total U.S.</td>
<td>Major Region</td>
<td>11</td>
<td>29</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">33041</td>
<td>2020-11-29</td>
<td>0.91</td>
<td>5811114.22</td>
<td>1352877.53</td>
<td>589061.83</td>
<td>19741.90</td>
<td>3790665.29</td>
<td>2197611.02</td>
<td>1531530.14</td>
<td>61524.13</td>
<td>conventional</td>
<td>2020</td>
<td>West</td>
<td>Major Region</td>
<td>11</td>
<td>29</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">33042</td>
<td>2020-11-29</td>
<td>1.48</td>
<td>289961.27</td>
<td>13273.75</td>
<td>19341.09</td>
<td>636.51</td>
<td>256709.92</td>
<td>122606.21</td>
<td>134103.71</td>
<td>0.00</td>
<td>organic</td>
<td>2020</td>
<td>West</td>
<td>Major Region</td>
<td>11</td>
<td>29</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">33043</td>
<td>2020-11-29</td>
<td>0.67</td>
<td>822818.75</td>
<td>234688.01</td>
<td>80205.15</td>
<td>10543.63</td>
<td>497381.96</td>
<td>285764.11</td>
<td>210808.02</td>
<td>809.83</td>
<td>conventional</td>
<td>2020</td>
<td>West Tex/New Mexico</td>
<td>Metro Area</td>
<td>11</td>
<td>29</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">33044</td>
<td>2020-11-29</td>
<td>1.35</td>
<td>24106.58</td>
<td>1236.96</td>
<td>617.80</td>
<td>1564.98</td>
<td>20686.84</td>
<td>17824.52</td>
<td>2862.32</td>
<td>0.00</td>
<td>organic</td>
<td>2020</td>
<td>West Tex/New Mexico</td>
<td>Metro Area</td>
<td>11</td>
<td>29</td>
</tr>
</tbody>
</table>

<p>33045 rows × 16 columns</p>
</div>
</div>
</div>
<div id="cell-15" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert values from scientific notation to standard decimal notation</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.float_format'</span>, <span class="st">'</span><span class="sc">{:.2f}</span><span class="st">'</span>.<span class="bu">format</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-16" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the DataFrame for the year 2017 and organic avocados</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>average_volume_by_month <span class="op">=</span> clean_df.groupby(<span class="st">'month'</span>)[<span class="st">'total_volume'</span>].mean()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>max_month <span class="op">=</span> average_volume_by_month.idxmax()</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(average_volume_by_month)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(max_month)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>month
1     985312.16
2    1095373.83
3     995715.04
4    1016581.69
5    1123632.25
6    1051246.57
7     983268.10
8     949924.93
9     906477.26
10    844686.29
11    822347.02
12    807669.47
Name: total_volume, dtype: float64
5
month
1     985312.16
2    1095373.83
3     995715.04
4    1016581.69
5    1123632.25
6    1051246.57
7     983268.10
8     949924.93
9     906477.26
10    844686.29
11    822347.02
12    807669.47
Name: total_volume, dtype: float64
5</code></pre>
</div>
</div>
<p>May (month #5) was the month with the highest average volume of avocado sales at 1123632.25</p>
<p>Problem 5 - Which metro area geographical regions sold the most total avocados? Plot side-by-side box-plots of the total volume for only the five metro geographical regions with the highest averages for the total_volume variable.</p>
<div id="cell-19" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>metro_area <span class="op">=</span> clean_df[clean_df[<span class="st">'region_type'</span>] <span class="op">==</span> <span class="st">'Metro Area'</span>]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>volume_by_metro_region <span class="op">=</span> metro_area.groupby(<span class="st">'region'</span>)[<span class="st">'total_volume'</span>].<span class="bu">sum</span>()</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>top_five_metro_areas <span class="op">=</span> volume_by_metro_region.nlargest(<span class="dv">5</span>).index</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>top_five_data <span class="op">=</span> metro_area[metro_area[<span class="st">'region'</span>].isin(top_five_metro_areas)]</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(top_five_metro_areas)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index(['South Central', 'Southeast', 'Great Lakes', 'Midsouth', 'Los Angeles'], dtype='object', name='region')
Index(['South Central', 'Southeast', 'Great Lakes', 'Midsouth', 'Los Angeles'], dtype='object', name='region')</code></pre>
</div>
</div>
<p>The South Central region is the region that sold the most amount of total avocados.</p>
<div id="cell-21" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#HELP WHY ARE ALL MY BOX PLOTS MESSED UP</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Using plotnine to create side by side box plots</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>(ggplot(top_five_data,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>aes(</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  x <span class="op">=</span> <span class="st">"region"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  y <span class="op">=</span> <span class="st">"total_volume"</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="op">+</span> geom_boxplot()</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a> <span class="op">+</span> labs(title<span class="op">=</span><span class="st">'Box Plots of Total Volume for Top 5 Metro Areas'</span>, x<span class="op">=</span><span class="st">'Metro Area'</span>, y<span class="op">=</span><span class="st">'Total Volume'</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="op">+</span> facet_wrap(<span class="st">'region'</span>, ncol<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="op">+</span> theme(axis_text_x<span class="op">=</span>element_text(rotation<span class="op">=</span><span class="dv">45</span>, hjust<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab2_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Problem 6 - From your cleaned data set, create a data set with only these California regions and answer the following questions about these California regions only.</p>
<div id="cell-23" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the California regions</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>california_regions <span class="op">=</span> [<span class="st">'Los Angeles'</span>, <span class="st">'San Diego'</span>, <span class="st">'Sacramento'</span>, <span class="st">'San Francisco'</span>]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the cleaned DataFrame to include only rows from these California regions</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>california_df <span class="op">=</span> clean_df[clean_df[<span class="st">'region'</span>].isin(california_regions)]</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows of the California data to verify the filter worked</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(california_df.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         date  average_price  total_volume  small_avocados  large_avocados  ...  year       region  region_type  month  day
44 2015-01-04           0.85    2682159.95      1837999.65       524430.47  ...  2015  Los Angeles   Metro Area      1    4
45 2015-01-04           1.25      54495.54        47721.51         1723.40  ...  2015  Los Angeles   Metro Area      1    4
80 2015-01-04           1.05     430138.88       110693.69       270107.61  ...  2015   Sacramento   Metro Area      1    4
81 2015-01-04           1.33       9213.49         3727.52         4327.52  ...  2015   Sacramento   Metro Area      1    4
82 2015-01-04           0.94     461607.33       244152.26       165299.33  ...  2015    San Diego   Metro Area      1    4

[5 rows x 16 columns]
         date  average_price  total_volume  small_avocados  large_avocados  ...  year       region  region_type  month  day
44 2015-01-04           0.85    2682159.95      1837999.65       524430.47  ...  2015  Los Angeles   Metro Area      1    4
45 2015-01-04           1.25      54495.54        47721.51         1723.40  ...  2015  Los Angeles   Metro Area      1    4
80 2015-01-04           1.05     430138.88       110693.69       270107.61  ...  2015   Sacramento   Metro Area      1    4
81 2015-01-04           1.33       9213.49         3727.52         4327.52  ...  2015   Sacramento   Metro Area      1    4
82 2015-01-04           0.94     461607.33       244152.26       165299.33  ...  2015    San Diego   Metro Area      1    4

[5 rows x 16 columns]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\sjacob17\AppData\Local\anaconda3\Lib\pprint.py:632: FutureWarning: Using repr(plot) to draw and show the plot figure is deprecated and will be removed in a future version. Use plot.show().</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab2_files/figure-html/cell-15-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Problem 7 - In which California regions is the price of organic versus conventional avocados most different? Support your answer with a few summary statistics AND a visualization.</p>
<div id="cell-25" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group the data by region and type, then calculate the mean price</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>average_price_by_type <span class="op">=</span> california_df.groupby([<span class="st">'region'</span>, <span class="st">'type'</span>])[<span class="st">'average_price'</span>].mean().unstack()</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the result to check</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(average_price_by_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>type           conventional  organic
region                              
Los Angeles            1.05     1.57
Sacramento             1.30     1.87
San Diego              1.11     1.80
San Francisco          1.40     2.12
type           conventional  organic
region                              
Los Angeles            1.05     1.57
Sacramento             1.30     1.87
San Diego              1.11     1.80
San Francisco          1.40     2.12</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\sjacob17\AppData\Local\anaconda3\Lib\pprint.py:632: FutureWarning: Using repr(plot) to draw and show the plot figure is deprecated and will be removed in a future version. Use plot.show().</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab2_files/figure-html/cell-16-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-26" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the price difference between organic and conventional avocados</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>average_price_by_type[<span class="st">'price_difference'</span>] <span class="op">=</span> average_price_by_type[<span class="st">'organic'</span>] <span class="op">-</span> average_price_by_type[<span class="st">'conventional'</span>]</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the result with the price differences</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(average_price_by_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>type           conventional  organic  price_difference
region                                                
Los Angeles            1.05     1.57              0.53
Sacramento             1.30     1.87              0.58
San Diego              1.11     1.80              0.68
San Francisco          1.40     2.12              0.72
type           conventional  organic  price_difference
region                                                
Los Angeles            1.05     1.57              0.53
Sacramento             1.30     1.87              0.58
San Diego              1.11     1.80              0.68
San Francisco          1.40     2.12              0.72</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\sjacob17\AppData\Local\anaconda3\Lib\pprint.py:632: FutureWarning: Using repr(plot) to draw and show the plot figure is deprecated and will be removed in a future version. Use plot.show().</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab2_files/figure-html/cell-17-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The San Francisco region has the largest price difference between organic and conventional avocados.</p>
<div id="cell-28" class="cell" data-execution_count="68">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    ggplot(average_price_by_type, aes(x<span class="op">=</span><span class="st">'region'</span>, y<span class="op">=</span><span class="st">'price_difference'</span>, fill<span class="op">=</span><span class="st">'region'</span>))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> geom_bar(stat<span class="op">=</span><span class="st">'identity'</span>) </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> labs(title<span class="op">=</span><span class="st">'Price Difference Between Organic and Conventional Avocados in California Regions'</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>           x<span class="op">=</span><span class="st">'Region'</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>           y<span class="op">=</span><span class="st">'Price Difference ($)'</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> theme_classic()</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> theme(plot_title<span class="op">=</span>element_text(size<span class="op">=</span><span class="dv">9</span>))</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab2_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\sjacob17\AppData\Local\anaconda3\Lib\pprint.py:632: FutureWarning: Using repr(plot) to draw and show the plot figure is deprecated and will be removed in a future version. Use plot.show().</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab2_files/figure-html/cell-18-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Problem 8 - Recreate the plot, for all four California regions, the proportion of the average Hass avocado sales that are small, large, or extra large; conventional vs.&nbsp;organic.</p>
<div id="cell-30" class="cell" data-execution_count="74">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Melt the data so 'small_avocados', 'large_avocados', and 'xl_avocados' become a single 'size' column</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>melted_data <span class="op">=</span> pd.melt(</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    california_df,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    id_vars<span class="op">=</span>[<span class="st">'region'</span>, <span class="st">'type'</span>],  <span class="co"># Keep region and type columns as is</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    value_vars<span class="op">=</span>[<span class="st">'small_avocados'</span>, <span class="st">'large_avocados'</span>, <span class="st">'xl_avocados'</span>],  <span class="co"># Columns to melt</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    var_name<span class="op">=</span><span class="st">'size'</span>,  <span class="co"># New column that will indicate the size category</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    value_name<span class="op">=</span><span class="st">'avocado_volume'</span>  <span class="co"># Avoid naming conflict by choosing a different value name</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename 'small_avocados', 'large_avocados', and 'xl_avocados' to 'Small', 'Large', 'Xlarge'</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>melted_data[<span class="st">'size'</span>] <span class="op">=</span> melted_data[<span class="st">'size'</span>].replace({</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'small_avocados'</span>: <span class="st">'Small'</span>,</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'large_avocados'</span>: <span class="st">'Large'</span>,</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'xl_avocados'</span>: <span class="st">'Xlarge'</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by region, type (organic/conventional), and size (Small, Large, Xlarge) and calculate the sum of avocado_volume</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>grouped_data <span class="op">=</span> melted_data.groupby([<span class="st">'region'</span>, <span class="st">'type'</span>, <span class="st">'size'</span>])[<span class="st">'avocado_volume'</span>].<span class="bu">sum</span>().reset_index()</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a dataframe with total volumes for each 'region' and 'type' (conventional/organic)</span></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>total_volumes <span class="op">=</span> grouped_data.groupby([<span class="st">'region'</span>, <span class="st">'type'</span>])[<span class="st">'avocado_volume'</span>].<span class="bu">sum</span>().reset_index()</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the column to avoid confusion</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>total_volumes.rename(columns<span class="op">=</span>{<span class="st">'avocado_volume'</span>: <span class="st">'total_volume_by_region_type'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the total volumes back to the original grouped data to calculate proportions</span></span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>grouped_data <span class="op">=</span> pd.merge(grouped_data, total_volumes, on<span class="op">=</span>[<span class="st">'region'</span>, <span class="st">'type'</span>])</span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the proportion of each size category within each region and type</span></span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a>grouped_data[<span class="st">'proportion'</span>] <span class="op">=</span> grouped_data[<span class="st">'avocado_volume'</span>] <span class="op">/</span> grouped_data[<span class="st">'total_volume_by_region_type'</span>]</span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the extra column for cleaner output if not needed</span></span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a>grouped_data.drop(columns<span class="op">=</span><span class="st">'total_volume_by_region_type'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the transformed dataset</span></span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grouped_data.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        region          type    size  avocado_volume  proportion
0  Los Angeles  conventional   Large    135815746.42        0.26
1  Los Angeles  conventional   Small    358923415.42        0.68
2  Los Angeles  conventional  Xlarge     29704534.92        0.06
3  Los Angeles       organic   Large      6366091.52        0.59
4  Los Angeles       organic   Small      4419271.78        0.41
        region          type    size  avocado_volume  proportion
0  Los Angeles  conventional   Large    135815746.42        0.26
1  Los Angeles  conventional   Small    358923415.42        0.68
2  Los Angeles  conventional  Xlarge     29704534.92        0.06
3  Los Angeles       organic   Large      6366091.52        0.59
4  Los Angeles       organic   Small      4419271.78        0.41</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\sjacob17\AppData\Local\anaconda3\Lib\pprint.py:632: FutureWarning: Using repr(plot) to draw and show the plot figure is deprecated and will be removed in a future version. Use plot.show().</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab2_files/figure-html/cell-19-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-31" class="cell" data-execution_count="79">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the order of the 'size' column to Xlarge, Large, Small</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>size_order <span class="op">=</span> [<span class="st">'Xlarge'</span>, <span class="st">'Large'</span>, <span class="st">'Small'</span>]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>grouped_data[<span class="st">'size'</span>] <span class="op">=</span> pd.Categorical(grouped_data[<span class="st">'size'</span>], categories<span class="op">=</span>size_order, ordered<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a custom function to format the y-axis as percentages</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> percent_formatter(values):</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [<span class="ss">f'</span><span class="sc">{</span>v<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%'</span> <span class="cf">for</span> v <span class="kw">in</span> values]</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    ggplot(grouped_data, aes(x<span class="op">=</span><span class="st">'region'</span>, y<span class="op">=</span><span class="st">'proportion'</span>, fill<span class="op">=</span><span class="st">'size'</span>))</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> geom_bar(stat<span class="op">=</span><span class="st">'identity'</span>, position<span class="op">=</span><span class="st">'stack'</span>)  <span class="co"># Create stacked bars for each size category</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> facet_wrap(<span class="st">'type'</span>)  <span class="co"># Facet by 'type' (conventional/organic)</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> labs(title<span class="op">=</span><span class="st">'Proportion of Average Hass Avocado Sales by Size'</span>, x<span class="op">=</span><span class="st">'Region of California'</span>, y<span class="op">=</span><span class="st">'Proportion'</span>)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> theme_classic()</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> theme(axis_text_x<span class="op">=</span>element_text(rotation<span class="op">=</span><span class="dv">45</span>, hjust<span class="op">=</span><span class="dv">1</span>))  <span class="co"># Rotate x-axis labels for readability</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>    <span class="op">+</span> scale_y_continuous(labels<span class="op">=</span>percent_formatter)  <span class="co"># Use the custom function to format y-axis as percentages</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab2_files/figure-html/cell-20-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\sjacob17\AppData\Local\anaconda3\Lib\pprint.py:632: FutureWarning: Using repr(plot) to draw and show the plot figure is deprecated and will be removed in a future version. Use plot.show().</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab2_files/figure-html/cell-20-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>